project:
  type: book
  output-dir: _book

book:
  title: "BM211 Workshops: Online supporting material"
  reader-mode: true
  
  cover-image: sipbs_compbio_800.png
  favicon: icon_32.png
  
  page-footer:
    left: |
      These BM211 workshop materials were written by Leighton Pritchard and Morgan Feeney.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  repo-url: https://github.com/sipbs-compbiol/BM211-workshops/
  repo-branch: main
  repo-actions: [edit, issue]

  author: "Dr Leighton Pritchard and Dr Morgan Feeney"
  date: "2024-02-16"
  
  chapters:
    - index.qmd
    
    - part: workshop_01_support.qmd
      chapters:
        - microbial_ecology.qmd
        - diversity_measures.qmd
        - shannon_index.qmd
#    - part: workshop_01.qmd
#        
#    - part: workshop_04.qmd
#      chapters: 
#        - piler_cr.qmd
#        
#    - part: workshop_05.qmd
#      chapters: 
#        - protein_trees.qmd
        
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - _extensions/course_format/theme.scss
    code-link: true

    author-meta: "Leighton Pritchard and Morgan Feeney"
    callout-appearance: simple
    
#  pdf:
#    documentclass: scrreprt

filters:
  - course_format


